theme: jekyll-theme-midnight
title: msfs2020-airport-CaseraRazzo
description: Altitude Airstrip in the Dolomiti Alps for Microsoft Flight Simulator
show_downloads: "true"

github:
  zip_url: https://github.com/nofaceinbook/msfs2020-airport-CaseraRazzo/releases/download/v0.1/airport-lid1-caserarazzo.zip
