theme: jekyll-theme-midnight
title: msfs2020-airport-CaseraRazzo
show_downloads: "true"

github:
  zip_url: https://github.com/nofaceinbook/msfs2020-airport-CaseraRazzo/releases/download/v0.1/airport-lid1-caserarazzo.zip
  
